version: "3.8"
services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379

  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    container_name: "keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080
  
  polar-ui:
    image: "ghcr.io/polarbookshop/polar-ui:demo"
    container_name: "polar-ui"
    ports:
      - 9004:9004
    environment:
      - PORT=9004
